#pragma once
/******************** 宏展开 **********************************/

/************************** 获取宏的参数个数 ********************/
#define ARG_N(...) \
    ARG_N_(0, ##__VA_ARGS__, ARG_N_RESQ)

#define ARG_N_(...) \
    ARG_N_M(__VA_ARGS__)

#define ARG_N_M(                                      \
    _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10,      \
    _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, \
    _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, \
    _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, \
    _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, \
    _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, \
    _61, _62, _63, N, ...) N

#define ARG_N_RESQ                              \
    63, 62, 61, 60,                             \
        59, 58, 57, 56, 55, 54, 53, 52, 51, 50, \
        49, 48, 47, 46, 45, 44, 43, 42, 41, 40, \
        39, 38, 37, 36, 35, 34, 33, 32, 31, 30, \
        29, 28, 27, 26, 25, 24, 23, 22, 21, 20, \
        19, 18, 17, 16, 15, 14, 13, 12, 11, 10, \
        9, 8, 7, 6, 5, 4, 3, 2, 1, 0

/************************** 将宏的参数展开 ********************/
#define EXPAND_ARG0()
#define EXPAND_ARG1(MALLOC, x) MALLOC(x)
#define EXPAND_ARG2(MALLOC, x, ...) MALLOC(x) EXPAND_ARG1(MALLOC, __VA_ARGS__)
#define EXPAND_ARG3(MALLOC, x, ...) MALLOC(x) EXPAND_ARG2(MALLOC, __VA_ARGS__)
#define EXPAND_ARG4(MALLOC, x, ...) MALLOC(x) EXPAND_ARG3(MALLOC, __VA_ARGS__)
#define EXPAND_ARG5(MALLOC, x, ...) MALLOC(x) EXPAND_ARG4(MALLOC, __VA_ARGS__)
#define EXPAND_ARG6(MALLOC, x, ...) MALLOC(x) EXPAND_ARG5(MALLOC, __VA_ARGS__)
#define EXPAND_ARG7(MALLOC, x, ...) MALLOC(x) EXPAND_ARG6(MALLOC, __VA_ARGS__)
#define EXPAND_ARG8(MALLOC, x, ...) MALLOC(x) EXPAND_ARG7(MALLOC, __VA_ARGS__)
#define EXPAND_ARG9(MALLOC, x, ...) MALLOC(x) EXPAND_ARG8(MALLOC, __VA_ARGS__)
#define EXPAND_ARG10(MALLOC, x, ...) MALLOC(x) EXPAND_ARG9(MALLOC, __VA_ARGS__)
#define EXPAND_ARG11(MALLOC, x, ...) MALLOC(x) EXPAND_ARG10(MALLOC, __VA_ARGS__)
#define EXPAND_ARG12(MALLOC, x, ...) MALLOC(x) EXPAND_ARG11(MALLOC, __VA_ARGS__)
#define EXPAND_ARG13(MALLOC, x, ...) MALLOC(x) EXPAND_ARG12(MALLOC, __VA_ARGS__)
#define EXPAND_ARG14(MALLOC, x, ...) MALLOC(x) EXPAND_ARG13(MALLOC, __VA_ARGS__)
#define EXPAND_ARG15(MALLOC, x, ...) MALLOC(x) EXPAND_ARG14(MALLOC, __VA_ARGS__)
#define EXPAND_ARG16(MALLOC, x, ...) MALLOC(x) EXPAND_ARG15(MALLOC, __VA_ARGS__)
#define EXPAND_ARG17(MALLOC, x, ...) MALLOC(x) EXPAND_ARG16(MALLOC, __VA_ARGS__)
#define EXPAND_ARG18(MALLOC, x, ...) MALLOC(x) EXPAND_ARG17(MALLOC, __VA_ARGS__)
#define EXPAND_ARG19(MALLOC, x, ...) MALLOC(x) EXPAND_ARG18(MALLOC, __VA_ARGS__)
#define EXPAND_ARG20(MALLOC, x, ...) MALLOC(x) EXPAND_ARG19(MALLOC, __VA_ARGS__)
#define EXPAND_ARG21(MALLOC, x, ...) MALLOC(x) EXPAND_ARG20(MALLOC, __VA_ARGS__)
#define EXPAND_ARG22(MALLOC, x, ...) MALLOC(x) EXPAND_ARG21(MALLOC, __VA_ARGS__)
#define EXPAND_ARG23(MALLOC, x, ...) MALLOC(x) EXPAND_ARG22(MALLOC, __VA_ARGS__)
#define EXPAND_ARG24(MALLOC, x, ...) MALLOC(x) EXPAND_ARG23(MALLOC, __VA_ARGS__)
#define EXPAND_ARG25(MALLOC, x, ...) MALLOC(x) EXPAND_ARG24(MALLOC, __VA_ARGS__)
#define EXPAND_ARG26(MALLOC, x, ...) MALLOC(x) EXPAND_ARG25(MALLOC, __VA_ARGS__)
#define EXPAND_ARG27(MALLOC, x, ...) MALLOC(x) EXPAND_ARG26(MALLOC, __VA_ARGS__)
#define EXPAND_ARG28(MALLOC, x, ...) MALLOC(x) EXPAND_ARG27(MALLOC, __VA_ARGS__)
#define EXPAND_ARG29(MALLOC, x, ...) MALLOC(x) EXPAND_ARG28(MALLOC, __VA_ARGS__)
#define EXPAND_ARG30(MALLOC, x, ...) MALLOC(x) EXPAND_ARG29(MALLOC, __VA_ARGS__)
#define EXPAND_ARG31(MALLOC, x, ...) MALLOC(x) EXPAND_ARG30(MALLOC, __VA_ARGS__)
#define EXPAND_ARG32(MALLOC, x, ...) MALLOC(x) EXPAND_ARG31(MALLOC, __VA_ARGS__)
#define EXPAND_ARG33(MALLOC, x, ...) MALLOC(x) EXPAND_ARG32(MALLOC, __VA_ARGS__)
#define EXPAND_ARG34(MALLOC, x, ...) MALLOC(x) EXPAND_ARG33(MALLOC, __VA_ARGS__)
#define EXPAND_ARG35(MALLOC, x, ...) MALLOC(x) EXPAND_ARG34(MALLOC, __VA_ARGS__)
#define EXPAND_ARG36(MALLOC, x, ...) MALLOC(x) EXPAND_ARG35(MALLOC, __VA_ARGS__)
#define EXPAND_ARG37(MALLOC, x, ...) MALLOC(x) EXPAND_ARG36(MALLOC, __VA_ARGS__)
#define EXPAND_ARG38(MALLOC, x, ...) MALLOC(x) EXPAND_ARG37(MALLOC, __VA_ARGS__)
#define EXPAND_ARG39(MALLOC, x, ...) MALLOC(x) EXPAND_ARG38(MALLOC, __VA_ARGS__)
#define EXPAND_ARG40(MALLOC, x, ...) MALLOC(x) EXPAND_ARG39(MALLOC, __VA_ARGS__)
#define EXPAND_ARG41(MALLOC, x, ...) MALLOC(x) EXPAND_ARG40(MALLOC, __VA_ARGS__)
#define EXPAND_ARG42(MALLOC, x, ...) MALLOC(x) EXPAND_ARG41(MALLOC, __VA_ARGS__)
#define EXPAND_ARG43(MALLOC, x, ...) MALLOC(x) EXPAND_ARG42(MALLOC, __VA_ARGS__)
#define EXPAND_ARG44(MALLOC, x, ...) MALLOC(x) EXPAND_ARG43(MALLOC, __VA_ARGS__)
#define EXPAND_ARG45(MALLOC, x, ...) MALLOC(x) EXPAND_ARG44(MALLOC, __VA_ARGS__)
#define EXPAND_ARG46(MALLOC, x, ...) MALLOC(x) EXPAND_ARG45(MALLOC, __VA_ARGS__)
#define EXPAND_ARG47(MALLOC, x, ...) MALLOC(x) EXPAND_ARG46(MALLOC, __VA_ARGS__)
#define EXPAND_ARG48(MALLOC, x, ...) MALLOC(x) EXPAND_ARG47(MALLOC, __VA_ARGS__)
#define EXPAND_ARG49(MALLOC, x, ...) MALLOC(x) EXPAND_ARG48(MALLOC, __VA_ARGS__)
#define EXPAND_ARG50(MALLOC, x, ...) MALLOC(x) EXPAND_ARG49(MALLOC, __VA_ARGS__)
#define EXPAND_ARG51(MALLOC, x, ...) MALLOC(x) EXPAND_ARG50(MALLOC, __VA_ARGS__)
#define EXPAND_ARG52(MALLOC, x, ...) MALLOC(x) EXPAND_ARG51(MALLOC, __VA_ARGS__)
#define EXPAND_ARG53(MALLOC, x, ...) MALLOC(x) EXPAND_ARG52(MALLOC, __VA_ARGS__)
#define EXPAND_ARG54(MALLOC, x, ...) MALLOC(x) EXPAND_ARG53(MALLOC, __VA_ARGS__)
#define EXPAND_ARG55(MALLOC, x, ...) MALLOC(x) EXPAND_ARG54(MALLOC, __VA_ARGS__)
#define EXPAND_ARG56(MALLOC, x, ...) MALLOC(x) EXPAND_ARG55(MALLOC, __VA_ARGS__)
#define EXPAND_ARG57(MALLOC, x, ...) MALLOC(x) EXPAND_ARG56(MALLOC, __VA_ARGS__)
#define EXPAND_ARG58(MALLOC, x, ...) MALLOC(x) EXPAND_ARG57(MALLOC, __VA_ARGS__)
#define EXPAND_ARG59(MALLOC, x, ...) MALLOC(x) EXPAND_ARG58(MALLOC, __VA_ARGS__)
#define EXPAND_ARG60(MALLOC, x, ...) MALLOC(x) EXPAND_ARG59(MALLOC, __VA_ARGS__)
#define EXPAND_ARG61(MALLOC, x, ...) MALLOC(x) EXPAND_ARG60(MALLOC, __VA_ARGS__)
#define EXPAND_ARG62(MALLOC, x, ...) MALLOC(x) EXPAND_ARG61(MALLOC, __VA_ARGS__)
#define EXPAND_ARG63(MALLOC, x, ...) MALLOC(x) EXPAND_ARG62(MALLOC, __VA_ARGS__)

#define ARG_CONCAT_(l, r) l##r
#define ARG_CONCAT(l, r) ARG_CONCAT_(l, r)

/************************** 对外调用的接口 ********************/
/******** 拼接前缀EXPAND_ARG和对应的数字，获得对应的用于展开的宏 ***********/
#define EXPAND(MALLOC, ...) ARG_CONCAT(EXPAND_ARG, ARG_N(__VA_ARGS__))(MALLOC, __VA_ARGS__)
